name: Build, Test, Create Image

on:
  push:
    branches: [ master, session* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd build
        bash build.sh

